### ISSUE TITLE
other library relations impl

### ISSUE THREAD

**Issue by BoxyUwU** [iiYese/aery#2]
It's cool to see people working on library relations, have you seen https://github.com/BoxyUwU/librelations its out of date but relies on a fork of bevy_ecs to allow for despawning entities to also despawn the targets of their relations. I don't do anything with bevy anymore these days, best of luck with your relations impl and hope my previous impl might be interesting to you

**Comment by iiYese** [comment]
I have. This was originally developed as a fork of bevy as a uni project. After learning more as I tinkered and seeing Flecs come out with [flattening](https://twitter.com/ajmmertens/status/1639725947258822656). I didn't want to pursue this as the cannonical solution for Bevy. Nevertheless what I did make made the entity in component pattern generic as well as greatly sugar all of the operations so I stripped it to only that and made it a lib because that alone is still plenty useful :)
